version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass' 
      MYSQL_DATABASE: 'memories'    
      MYSQL_USER: 'user'          
      MYSQL_PASSWORD: 'pass'     
    volumes:
      - mysqlvol:/var/lib/mysql

  apigo:
    image: gerhardardon/apigo:latest
    pid: host
    restart: always
    volumes:
    - type: bind
      source: /proc
      target: /proc
    ports:
      - "3000:3000"
    depends_on:
      - db


  frontend:
    image: gerhardardon/frontreact:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - apigo

volumes:
  mysqlvol:
